name: url_update

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'check codes' 
      uses: actions/checkout@v2
      
    - name: 'bash url_update.sh'
      run: |
        sudo cp ./sources.list /etc/apt/
        sudo apt update -y
        sudo apt upgrade -y
        rm index.html -rf
        cp index.backup index.html
        chmod 777 ./*
        echo "------- 开始执行 url_update.sh --------"
        bash ./url_update.sh
        echo "-------- 成功 ---------------"
        echo "----------- 打印index.html  ------------------"
        ls -al ./
        cat index.html
        echo "--------- 上面是 index.html ------------"
         
    - name: 'Deploy to gh-pages branch'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: master
        FOLDER: .
